package com.dental.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class BuildingDentalDesign extends AbsoluteLayout {
	protected Image backGround;
	protected Button bUitbreding1;
	protected Button bGebouw1;
	protected Button bGietZand;
	protected Button bStaalOpslTechn;
	protected Button bStock;
	protected Button bGieten;
	protected Button bMetaal1;
	protected Button bStaal1;
	protected Button bKronen;
	protected Button bMetaal2;
	protected Button bStaal2;
	protected Button bGarage;
	protected Button bBureauAlain;
	protected Button bLandscape2;
	protected Button bSpray;
	protected Button bMeten;
	protected Button bSecret;
	protected Button bZirconium;
	protected Button bPorcelein1;
	protected Button bPorcelein2;
	protected Button bKitchenette;
	protected Button bInkom;
	protected Button bLandscape1;

	public BuildingDentalDesign() {
		Design.read(this);
	}
}
